Dev
karthi07/apple-clone pull request #3
Opened 2020-03-12 20:34 UTC by karthi07

test

2020-03-12 20:48 UTC, karthi07 commented
Worked on following functionalities

Clone the Apple Web page
learnt and implemented z index
Multiple layout options
setting background image and positioning element according to it

PS : fixed lint error. after setting up github stickler plugin, the checks was mentioned in the comments [fixed all the lint errors on checking from comments] . let me know if it's possible to add to check.

2020-03-12 23:56 UTC, majovanilla requested changes
Hey @karthi07 , 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.
![Screenshot from 2020-03-12 17-32-42](https://user-images.githubusercontent.com/51926937/76576553-062a8080-6488-11ea-8314-5f8bb2dec079.png)

## Please, make all REQUIRED changes (check below, too) and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-13 00:01 UTC, majovanilla requested changes

2020-03-13 00:01 UTC, majovanilla commented on index.html
> +                        <div class="sr-img"></div>
- Your search icon is not showing. Please make it appear inside the search bar.

2020-03-13 00:01 UTC, majovanilla commented on index.html
> +        <footer>
- Your footer should be centered. Please fix it.

2020-03-13 00:01 UTC, majovanilla commented on index.html
> +                <a href="#">
Each `<li>` element should be an individual `<a>` tag

2020-03-13 00:01 UTC, majovanilla commented on index.html
> +                    <a href="#">
Each `<li>` element should be an individual `<a>` tag

2020-03-13 04:16 UTC, karthi07 commented on index.html
> +        <footer>
![Screenshot from 2020-03-13 09-43-15](https://user-images.githubusercontent.com/5237154/76589228-644e7680-650f-11ea-9ce5-d11ba8609dfc.png)
Footer is centered in my screen width settings, if not please share your width setting

2020-03-13 04:20 UTC, karthi07 commented
@majovanilla  Completed all the changes :) Regarding the footer width center, it works on my current screen size, let know which size need to be changed.

2020-03-13 05:56 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @karthi07 :handshake: 

### Thank you for fixing the changes requested by the previous reviewer :medal_sports: and good job taking care of all browsers when thinking in your navbar gradient :star: 

### Now we have to take care of your page looking good in all screens :point_down: 

## % for width

- [ ] I see you hardcoded values for width, try using percentages and make the heroe section background and aside content take 100% of the screen width, so it will look proportional in all screen sizes, in my screen is not only the footer that looks out of place is also the navbar almost overflows the heroe background

your page in my screen:

![image](https://user-images.githubusercontent.com/52209067/76593257-73a3d480-64bb-11ea-9782-499ccd0d29eb.png)

original in my screen:

![image](https://user-images.githubusercontent.com/52209067/76593277-7e5e6980-64bb-11ea-826b-bc36e6d67f17.png)

### That's it! :raised_hands: 

### Please :pray: fix this :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-03-13 06:38 UTC, karthi07 commented
Converted the hardcorded width to percentages for body (hero) and aside. Nav and footer's widht are in percentages. those sections works perfectly on inspect element responsive tab too. the screen settings are based on the apple page and background image. Tried all my possible options i know, let me know if i can change something here

2020-03-13 07:29 UTC, lekegitrepo commented
## Hi @karthi07 💯 
### You have done a great job by making the required changes and also for making the look almost as the original page. This project is approved 🥇 

### Consider the suggestion as optional:
- You try to add the hover effect in the navbar like the original.
- Make the apple logo a link (i.e. you can wrap it within a link tag.

### Reviewed by: Temitayo Adeleke.

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

2020-03-13 07:32 UTC, lekegitrepo approved these changes
### Status: Approved

2020-03-13 07:37 UTC, merged